routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontController@index')->name('front');
Route::get('/kategori/{slug}', 'FrontController@kategori')->name('kategori');
Route::get('/provinsi/{slug}', 'FrontController@provinsi')->name('provinsi');

Route::get('/search', 'FrontController@search');
Route::get('/searchprovinsi', 'FrontController@searchProvinsi')->name('searchprovinsi');


Route::get('/searchmobile', 'FrontController@search');
Route::get('/searchprovinsimobile', 'FrontController@searchProvinsi')->name('searchprovinsimobile');

Route::get('/detail/{slug}', 'FrontController@detail')->name('detail');
Route::post('/detail/{slug}', 'FrontController@comment')->name('comment.store');

Route::get('/donatur', 'FrontController@donatur')->name('donatur');
Route::post('/donatur', 'FrontController@donaturstore')->name('donaturstore');

Route::get('/daftar', 'RegistrasiController@index')->name('daftar');
Route::post('/daftar', 'RegistrasiController@store')->name('daftarsukses');
// Route::get('/daftar', 'RegistrasiController@index')->name('daftar');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->middleware('verified');

// Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:super-admin']], function () {

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:superadmin|admin|yayasan']], function () {
    Route::resource('users', 'Backend\UserController', ["as" => 'backend']);
    Route::resource('roles', 'Backend\RoleController', ["as" => 'backend']);
    Route::resource('permissions', 'Backend\PermissionController', ["as" => 'backend']);
    Route::resource('kategori', 'Backend\KategoriController', ["as" => 'backend']);
    Route::resource('provinsi', 'Backend\ProvinsiController', ["as" => 'backend']);
    Route::resource('konfirmasi', 'Backend\KonfirmasiController', ["as" => 'backend']);
    Route::resource('donatur', 'Backend\DonaturController', ["as" => 'backend']);
    Route::resource('comments', 'Backend\CommentsController', ["as" => 'backend']);
    Route::resource('slide', 'Backend\SlideController', ["as" => 'backend']);

});

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:yayasan|superadmin|admin']], function () {
    Route::resource('yayasan', 'Backend\YayasanController', ["as" => 'backend']);
});




Route::group(['prefix' => 'backend'], function () {
});

app/Models/Backend/Permission.php
<?php

namespace App\Models\Backend;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Models\Permission as BasePermission;

class Permission extends BasePermission
{
    use SoftDeletes;

    public $table = 'permissions';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'guard_name'
    ];

   
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'guard_name' => 'string'
    ];

    
    public static $rules = [
        'name' => 'required',
        'guard_name' => 'required'
    ];

}

app/Http/Controllers/API/Backend/UserAPIController.php
<?php

namespace App\Http\Controllers\API\Backend;

use App\Http\Controllers\AppBaseController;
use App\Http\Requests\API\Backend\CreateUserAPIRequest;
use App\Http\Requests\API\Backend\UpdateUserAPIRequest;
use App\Http\Resources\UserCollection;
use App\User;
use Illuminate\Http\Request;
use Response;

/**
 * Class UserController
 * @package App\Http\Controllers\API\Backend
 */

class UserAPIController extends AppBaseController
{
    /**
     * Display a listing of the User.
     * GET|HEAD /users
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        // return new UserCollection(User::get());
        $query = User::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $users = $query->get();

        // return $this->sendResponse($users->toArray(), 'Users retrieved successfully');
    }

    /**
     * Store a newly created User in storage.
     * POST /users
     *
     * @param CreateUserAPIRequest $request
     *
     * @return Response
     */
    public function store(CreateUserAPIRequest $request)
    {
        $input = $request->all();

        /** @var User $user */
        $user = User::create($input);

        return $this->sendResponse($user->toArray(), 'User saved successfully');
    }

    /**
     * Display the specified User.
     * GET|HEAD /users/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        return $this->sendResponse($user->toArray(), 'User retrieved successfully');
    }

    /**
     * Update the specified User in storage.
     * PUT/PATCH /users/{id}
     *
     * @param int $id
     * @param UpdateUserAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserAPIRequest $request)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        $user->fill($request->all());
        $user->save();

        return $this->sendResponse($user->toArray(), 'User updated successfully');
    }

    /**
     * Remove the specified User from storage.
     * DELETE /users/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        $user->delete();

        return $this->sendSuccess('User deleted successfully');
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\CommentsDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateCommentsRequest;
use App\Http\Requests\Backend\UpdateCommentsRequest;
use App\Models\Backend\Comments;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CommentsController extends AppBaseController
{
    /**
     * Display a listing of the Comments.
     *
     * @param CommentsDataTable $commentsDataTable
     * @return Response
     */
    public function index(CommentsDataTable $commentsDataTable)
    {
        return $commentsDataTable->render('backend.comments.index');
    }

    /**
     * Show the form for creating a new Comments.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.comments.create');
    }

    /**
     * Store a newly created Comments in storage.
     *
     * @param CreateCommentsRequest $request
     *
     * @return Response
     */
    public function store(CreateCommentsRequest $request)
    {
        $input = $request->all();

        /** @var Comments $comments */
        $comments = Comments::create($input);

        Flash::success('Comments saved successfully.');

        return redirect(route('backend.comments.index'));
    }

    /**
     * Display the specified Comments.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        return view('backend.comments.show')->with('comments', $comments);
    }

    /**
     * Show the form for editing the specified Comments.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        return view('backend.comments.edit')->with('comments', $comments);
    }

    /**
     * Update the specified Comments in storage.
     *
     * @param  int              $id
     * @param UpdateCommentsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCommentsRequest $request)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        $comments->fill($request->all());
        $comments->save();

        Flash::success('Comments updated successfully.');

        return redirect(route('backend.comments.index'));
    }

    /**
     * Remove the specified Comments from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        $comments->delete();

        Flash::success('Comments deleted successfully.');

        return redirect(route('backend.comments.index'));
    }
}

app/Http/Controllers/Backend/DonaturController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\DonaturDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateDonaturRequest;
use App\Http\Requests\Backend\UpdateDonaturRequest;
use App\Models\Backend\Donatur;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class DonaturController extends AppBaseController
{
    /**
     * Display a listing of the Donatur.
     *
     * @param DonaturDataTable $donaturDataTable
     * @return Response
     */
    public function index(DonaturDataTable $donaturDataTable)
    {
        return $donaturDataTable->render('backend.donatur.index');
    }

    /**
     * Show the form for creating a new Donatur.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.donatur.create');
    }

    /**
     * Store a newly created Donatur in storage.
     *
     * @param CreateDonaturRequest $request
     *
     * @return Response
     */
    public function store(CreateDonaturRequest $request)
    {
        $input = $request->all();

        /** @var Donatur $donatur */
        $donatur = Donatur::create($input);

        Flash::success('Donatur saved successfully.');

        return redirect(route('backend.donatur.index'));
    }

    /**
     * Display the specified Donatur.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        return view('backend.donatur.show')->with('donatur', $donatur);
    }

    /**
     * Show the form for editing the specified Donatur.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        return view('backend.donatur.edit')->with('donatur', $donatur);
    }

    /**
     * Update the specified Donatur in storage.
     *
     * @param  int              $id
     * @param UpdateDonaturRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDonaturRequest $request)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        $donatur->fill($request->all());
        $donatur->save();

        Flash::success('Donatur updated successfully.');

        return redirect(route('backend.donatur.index'));
    }

    /**
     * Remove the specified Donatur from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        $donatur->delete();

        Flash::success('Donatur deleted successfully.');

        return redirect(route('backend.donatur.index'));
    }
}

app/Http/Controllers/Backend/KategoriController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\KategoriDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateKategoriRequest;
use App\Http\Requests\Backend\UpdateKategoriRequest;
use App\Models\Backend\Kategori;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class KategoriController extends AppBaseController
{
    /**
     * Display a listing of the Kategori.
     *
     * @param KategoriDataTable $kategoriDataTable
     * @return Response
     */
    public function index(KategoriDataTable $kategoriDataTable)
    {
        return $kategoriDataTable->render('backend.kategori.index');
    }

    /**
     * Show the form for creating a new Kategori.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.kategori.create');
    }

    /**
     * Store a newly created Kategori in storage.
     *
     * @param CreateKategoriRequest $request
     *
     * @return Response
     */
    public function store(CreateKategoriRequest $request)
    {
        $input = $request->all();

        $kategori = Kategori::create($input);

        if($request->hasFile('banner') && $request->file('banner')->isValid()){
            $kategori->addMediaFromRequest('banner')->toMediaCollection('banner_image');
        }

        if($request->hasFile('icon') && $request->file('icon')->isValid()){
            $kategori->addMediaFromRequest('icon')->toMediaCollection('icon_image');
        }

        Flash::success('Kategori saved successfully.');

        return redirect(route('backend.kategori.index'));
    }

    
    public function show($id)
    {
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        return view('backend.kategori.show')->with('kategori', $kategori);
    }

    public function edit($id)
    {
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        return view('backend.kategori.edit')->with('kategori', $kategori);
    }

    
    public function update($id, UpdateKategoriRequest $request)
    {
        /** @var Kategori $kategori */
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        $kategori->fill($request->all());

        if ($kategori->hasMedia('banner')) {
            $kategori->updateMedia($kategori, 'banner_image'); //images === collection name
        } elseif ($request->hasFile('banner')) {
           $kategori->media()->delete($id);
           $kategori->addMediaFromRequest('banner')->toMediaCollection('banner_image');
        } 

        if ($kategori->hasMedia('icon')) {
            $kategori->updateMedia($kategori, 'icon_image'); //images === collection name
        } elseif ($request->hasFile('icon')) {
           $kategori->media()->delete($id);
           $kategori->addMediaFromRequest('icon')->toMediaCollection('icon_image');
        } 

        $kategori->save();

        Flash::success('Kategori updated successfully.');

        return redirect(route('backend.kategori.index'));
    }

    /**
     * Remove the specified Kategori from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Kategori $kategori */
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        $kategori->delete();

        Flash::success('Kategori deleted successfully.');

        return redirect(route('backend.kategori.index'));
    }
}

resources/views/backend/yayasan/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Yayasan</h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            {!! Form::open(['route' => 'backend.yayasan.store', 'files' => true, 'enctype' => 'multipart/form-data']) !!}
                                {!! Form::hidden('user_id', Auth::user()->id) !!}
                                
                                @include('backend.yayasan.fields')
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/yayasan/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.yayasan.destroy', $id], 'method' => 'delete']) !!}
    <a href="{{ route('backend.yayasan.show', $id) }}" class='btn btn-success btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('backend.yayasan.edit', $id) }}" class='btn btn-info btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
{!! Form::close() !!}

resources/views/backend/yayasan/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Yayasan
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            {!! Form::model($yayasan, ['route' => ['backend.yayasan.update', $yayasan->id], 'method' => 'patch', 'files' => true, 'enctype' => 'multipart/form-data']) !!}
                                {!! Form::hidden('user_id', $creator) !!}
                                <img src={{ $yayasan->getFirstMediaUrl('foto_image') }} width="350" style="margin-bottom:30px;padding: 20px">

                                @include('backend.yayasan.fields')
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </div>
@endsection

resources/views/backend/yayasan/fields.blade.php
<div class="form-group col-sm-12">
    {!! Form::label('foto', 'Foto:') !!}
    {!! Form::file('foto', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('kategori_id', 'Pilih Kategori:') !!}
    {!! Form::select('kategori_id', $kategori, null, ['class' => 'form-control', 'id' => 'select_kategori']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('provinces_id', 'Pilih Provinsi:') !!}
    {!! Form::select('provinces_id', $provinces, null, ['class' => 'form-control', 'id' => 'select_provinsi']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nama Yayasan:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Pemilik Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pemilik', 'Pemilik Yayasan:') !!}
    {!! Form::text('pemilik', null, ['class' => 'form-control']) !!}
</div>

<!-- No Izin Field -->
<div class="form-group col-sm-6">
    {!! Form::label('no_izin', 'No Izin Yayasan:') !!}
    {!! Form::text('no_izin', null, ['class' => 'form-control']) !!}
</div>

<!-- Nama Rekening Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_rekening', 'Nama Rekening:') !!}
    {!! Form::text('nama_rekening', null, ['class' => 'form-control']) !!}
</div>

<!-- No Rekening Field -->
<div class="form-group col-sm-6">
    {!! Form::label('no_rekening', 'No Rekening:') !!}
    {!! Form::text('no_rekening', null, ['class' => 'form-control']) !!}
</div>

<!-- Nama Bank Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_bank', 'Nama Bank:') !!}
    {!! Form::text('nama_bank', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Yayasan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email_yayasan', 'Email Yayasan:') !!}
    {!! Form::text('email_yayasan', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('web', 'Website:') !!}
    {!! Form::text('web', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'No Telp Yayasan:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('alamat', 'Alamat:') !!}
    {!! Form::text('alamat', null, ['class' => 'form-control']) !!}
</div>

@role('superadmin')
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status :') !!}
    {!! Form::select('status', $status, null, ['class' => 'form-control', 'id' => 'select_status']) !!}
</div>
@endrole
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Simpan', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.yayasan.index') }}" class="btn btn-default">Kembali</a>
</div>


@push('scripts')
    <script>
        $('#select_kategori').select2()
        $('#select_provinsi').select2()
        $('#select_status').select2()
    </script>
@endpush

resources/views/backend/yayasan/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Yayasan</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('backend.yayasan.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <form id="search-filter">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Range Tanggal:</label>
                                  <input type="text" name="filterdate" class="form-control" id="filterdate" placeholder="Pilih Tanggal">
                                  <input type="hidden" name="minDate" id="minDate">
                                  <input type="hidden" name="maxDate" id="maxDate">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Provinsi</label>
                                <select name="provinces_id" id="provinces_id" class="form-control" data-placeholder="Select ...">
                                    @foreach($provinsi as $provinsi)
                                        <option value=""></option>
                                        <option value="{{$provinsi->id}}">{{$provinsi->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Status</label>
                                <select name="status" id="status" class="form-control" data-placeholder="Select ...">
                                    @foreach($status as $status)
                                        <option value=""></option>
                                        <option value="{{$status}}">{{$status}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Filter</label>
                                <div class="">
                                    <a class="btn btn-default" href="{{route('backend.yayasan.index')}}">Reset</a>
                                    <button type="submit" class="btn btn-success">Filter</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('backend.yayasan.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            var reqTable = $(".table").DataTable();
            $('#status').select2()
                $('#provinces_id').select2()
            
            $('#search-filter').on('submit', function (e) {
                
                reqTable.draw();
                e.preventDefault();
            });

            $('.custom-select-master').select2()
        });
    </script>
    
          
          
          
        
@endpush

resources/views/backend/yayasan/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Yayasan</h1>
    </section>
    <div class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row" style="padding: 20px">
                            @include('backend.yayasan.show_fields')
                            <a href="{{ route('backend.yayasan.index') }}" class="btn btn-default">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/yayasan/show_fields.blade.php
<img src={{ $yayasan->getFirstMediaUrl('foto_image') }} width="350" style="margin-bottom:30px">
<table class="table table-responsive table-bordered table-striped">
    <thead>
        <tr>
            <th>Field</th>
            <th>Data</th>
        </tr>    
    </thead>
    <tbody>
        <tr>
            <td>{!! Form::label('kategori_id', 'Kategori') !!}</td>
            <td>{{ $yayasan->kategori->name }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('provinces_id', 'Provinsi') !!}</td>
            <td>{{ $yayasan->provinsi->name }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('name', 'Nama Yayasan') !!}</td>
            <td>{{ $yayasan->name }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('pemilik', 'Nama Pemilik Yayasan') !!}</td>
            <td>{{ $yayasan->pemilik }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('no_izin', 'No Perizinan') !!}</td>
            <td>{{ $yayasan->no_izin }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('nama_rekening', 'Nama Rekening Yayasan') !!}</td>
            <td>{{ $yayasan->nama_rekening }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('no_rekening', 'No Rekening') !!}</td>
            <td>{{ $yayasan->no_rekening }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('nama_bank', 'Nama Bank') !!}</td>
            <td>{{ $yayasan->nama_bank }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('email_yayasan', 'Email') !!}</td>
            <td>{{ $yayasan->email_yayasan }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('phone', 'No Telepon Yayasan') !!}</td>
            <td>{{ $yayasan->phone }}</td>
        </tr>
        <tr>
            <td>{!! Form::label('alamat', 'Alamat Yayasan') !!}</td>
            <td>{{ $yayasan->alamat }}</td>
        </tr>
    </tbody>
</table>