routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontController@index')->name('front');
Route::get('/kategori/{slug}', 'FrontController@kategori')->name('kategori');
Route::get('/provinsi/{slug}', 'FrontController@provinsi')->name('provinsi');

Route::get('/search', 'FrontController@search');
Route::get('/searchprovinsi', 'FrontController@searchProvinsi')->name('searchprovinsi');


Route::get('/searchmobile', 'FrontController@search');
Route::get('/searchprovinsimobile', 'FrontController@searchProvinsi')->name('searchprovinsimobile');

Route::get('/detail/{slug}', 'FrontController@detail')->name('detail');
Route::post('/detail/{slug}', 'FrontController@comment')->name('comment.store');

Route::get('/donatur', 'FrontController@donatur')->name('donatur');
Route::post('/donatur', 'FrontController@donaturstore')->name('donaturstore');

Route::get('/daftar', 'RegistrasiController@index')->name('daftar');
Route::post('/daftar', 'RegistrasiController@store')->name('daftarsukses');
// Route::get('/daftar', 'RegistrasiController@index')->name('daftar');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->middleware('verified');

// Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:super-admin']], function () {

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:superadmin|admin|yayasan']], function () {
    Route::resource('users', 'Backend\UserController', ["as" => 'backend']);
    Route::resource('roles', 'Backend\RoleController', ["as" => 'backend']);
    Route::resource('permissions', 'Backend\PermissionController', ["as" => 'backend']);
    Route::resource('kategori', 'Backend\KategoriController', ["as" => 'backend']);
    Route::resource('provinsi', 'Backend\ProvinsiController', ["as" => 'backend']);
    Route::resource('konfirmasi', 'Backend\KonfirmasiController', ["as" => 'backend']);
    Route::resource('donatur', 'Backend\DonaturController', ["as" => 'backend']);
    Route::resource('comments', 'Backend\CommentsController', ["as" => 'backend']);
    Route::resource('slide', 'Backend\SlideController', ["as" => 'backend']);

});

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:yayasan|superadmin|admin']], function () {
    Route::resource('yayasan', 'Backend\YayasanController', ["as" => 'backend']);
});




Route::group(['prefix' => 'backend'], function () {
});

app/Models/Backend/Permission.php
<?php

namespace App\Models\Backend;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Models\Permission as BasePermission;

class Permission extends BasePermission
{
    use SoftDeletes;

    public $table = 'permissions';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'guard_name'
    ];

   
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'guard_name' => 'string'
    ];

    
    public static $rules = [
        'name' => 'required',
        'guard_name' => 'required'
    ];

}

app/Http/Controllers/API/Backend/UserAPIController.php
<?php

namespace App\Http\Controllers\API\Backend;

use App\Http\Controllers\AppBaseController;
use App\Http\Requests\API\Backend\CreateUserAPIRequest;
use App\Http\Requests\API\Backend\UpdateUserAPIRequest;
use App\Http\Resources\UserCollection;
use App\User;
use Illuminate\Http\Request;
use Response;

/**
 * Class UserController
 * @package App\Http\Controllers\API\Backend
 */

class UserAPIController extends AppBaseController
{
    /**
     * Display a listing of the User.
     * GET|HEAD /users
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        // return new UserCollection(User::get());
        $query = User::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $users = $query->get();

        // return $this->sendResponse($users->toArray(), 'Users retrieved successfully');
    }

    /**
     * Store a newly created User in storage.
     * POST /users
     *
     * @param CreateUserAPIRequest $request
     *
     * @return Response
     */
    public function store(CreateUserAPIRequest $request)
    {
        $input = $request->all();

        /** @var User $user */
        $user = User::create($input);

        return $this->sendResponse($user->toArray(), 'User saved successfully');
    }

    /**
     * Display the specified User.
     * GET|HEAD /users/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        return $this->sendResponse($user->toArray(), 'User retrieved successfully');
    }

    /**
     * Update the specified User in storage.
     * PUT/PATCH /users/{id}
     *
     * @param int $id
     * @param UpdateUserAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserAPIRequest $request)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        $user->fill($request->all());
        $user->save();

        return $this->sendResponse($user->toArray(), 'User updated successfully');
    }

    /**
     * Remove the specified User from storage.
     * DELETE /users/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var User $user */
        $user = User::find($id);

        if (empty($user)) {
            return $this->sendError('User not found');
        }

        $user->delete();

        return $this->sendSuccess('User deleted successfully');
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\CommentsDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateCommentsRequest;
use App\Http\Requests\Backend\UpdateCommentsRequest;
use App\Models\Backend\Comments;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CommentsController extends AppBaseController
{
    /**
     * Display a listing of the Comments.
     *
     * @param CommentsDataTable $commentsDataTable
     * @return Response
     */
    public function index(CommentsDataTable $commentsDataTable)
    {
        return $commentsDataTable->render('backend.comments.index');
    }

    /**
     * Show the form for creating a new Comments.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.comments.create');
    }

    /**
     * Store a newly created Comments in storage.
     *
     * @param CreateCommentsRequest $request
     *
     * @return Response
     */
    public function store(CreateCommentsRequest $request)
    {
        $input = $request->all();

        /** @var Comments $comments */
        $comments = Comments::create($input);

        Flash::success('Comments saved successfully.');

        return redirect(route('backend.comments.index'));
    }

    /**
     * Display the specified Comments.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        return view('backend.comments.show')->with('comments', $comments);
    }

    /**
     * Show the form for editing the specified Comments.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        return view('backend.comments.edit')->with('comments', $comments);
    }

    /**
     * Update the specified Comments in storage.
     *
     * @param  int              $id
     * @param UpdateCommentsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCommentsRequest $request)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        $comments->fill($request->all());
        $comments->save();

        Flash::success('Comments updated successfully.');

        return redirect(route('backend.comments.index'));
    }

    /**
     * Remove the specified Comments from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Comments $comments */
        $comments = Comments::find($id);

        if (empty($comments)) {
            Flash::error('Comments not found');

            return redirect(route('backend.comments.index'));
        }

        $comments->delete();

        Flash::success('Comments deleted successfully.');

        return redirect(route('backend.comments.index'));
    }
}

app/Http/Controllers/Backend/DonaturController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\DonaturDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateDonaturRequest;
use App\Http\Requests\Backend\UpdateDonaturRequest;
use App\Models\Backend\Donatur;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class DonaturController extends AppBaseController
{
    /**
     * Display a listing of the Donatur.
     *
     * @param DonaturDataTable $donaturDataTable
     * @return Response
     */
    public function index(DonaturDataTable $donaturDataTable)
    {
        return $donaturDataTable->render('backend.donatur.index');
    }

    /**
     * Show the form for creating a new Donatur.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.donatur.create');
    }

    /**
     * Store a newly created Donatur in storage.
     *
     * @param CreateDonaturRequest $request
     *
     * @return Response
     */
    public function store(CreateDonaturRequest $request)
    {
        $input = $request->all();

        /** @var Donatur $donatur */
        $donatur = Donatur::create($input);

        Flash::success('Donatur saved successfully.');

        return redirect(route('backend.donatur.index'));
    }

    /**
     * Display the specified Donatur.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        return view('backend.donatur.show')->with('donatur', $donatur);
    }

    /**
     * Show the form for editing the specified Donatur.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        return view('backend.donatur.edit')->with('donatur', $donatur);
    }

    /**
     * Update the specified Donatur in storage.
     *
     * @param  int              $id
     * @param UpdateDonaturRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDonaturRequest $request)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        $donatur->fill($request->all());
        $donatur->save();

        Flash::success('Donatur updated successfully.');

        return redirect(route('backend.donatur.index'));
    }

    /**
     * Remove the specified Donatur from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Donatur $donatur */
        $donatur = Donatur::find($id);

        if (empty($donatur)) {
            Flash::error('Donatur not found');

            return redirect(route('backend.donatur.index'));
        }

        $donatur->delete();

        Flash::success('Donatur deleted successfully.');

        return redirect(route('backend.donatur.index'));
    }
}

app/Http/Controllers/Backend/KategoriController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\Backend\KategoriDataTable;
use App\Http\Requests\Backend;
use App\Http\Requests\Backend\CreateKategoriRequest;
use App\Http\Requests\Backend\UpdateKategoriRequest;
use App\Models\Backend\Kategori;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class KategoriController extends AppBaseController
{
    /**
     * Display a listing of the Kategori.
     *
     * @param KategoriDataTable $kategoriDataTable
     * @return Response
     */
    public function index(KategoriDataTable $kategoriDataTable)
    {
        return $kategoriDataTable->render('backend.kategori.index');
    }

    /**
     * Show the form for creating a new Kategori.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.kategori.create');
    }

    /**
     * Store a newly created Kategori in storage.
     *
     * @param CreateKategoriRequest $request
     *
     * @return Response
     */
    public function store(CreateKategoriRequest $request)
    {
        $input = $request->all();

        $kategori = Kategori::create($input);

        if($request->hasFile('banner') && $request->file('banner')->isValid()){
            $kategori->addMediaFromRequest('banner')->toMediaCollection('banner_image');
        }

        if($request->hasFile('icon') && $request->file('icon')->isValid()){
            $kategori->addMediaFromRequest('icon')->toMediaCollection('icon_image');
        }

        Flash::success('Kategori saved successfully.');

        return redirect(route('backend.kategori.index'));
    }

    
    public function show($id)
    {
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        return view('backend.kategori.show')->with('kategori', $kategori);
    }

    public function edit($id)
    {
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        return view('backend.kategori.edit')->with('kategori', $kategori);
    }

    
    public function update($id, UpdateKategoriRequest $request)
    {
        /** @var Kategori $kategori */
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        $kategori->fill($request->all());

        if ($kategori->hasMedia('banner')) {
            $kategori->updateMedia($kategori, 'banner_image'); //images === collection name
        } elseif ($request->hasFile('banner')) {
           $kategori->media()->delete($id);
           $kategori->addMediaFromRequest('banner')->toMediaCollection('banner_image');
        } 

        if ($kategori->hasMedia('icon')) {
            $kategori->updateMedia($kategori, 'icon_image'); //images === collection name
        } elseif ($request->hasFile('icon')) {
           $kategori->media()->delete($id);
           $kategori->addMediaFromRequest('icon')->toMediaCollection('icon_image');
        } 

        $kategori->save();

        Flash::success('Kategori updated successfully.');

        return redirect(route('backend.kategori.index'));
    }

    /**
     * Remove the specified Kategori from storage.
     *
     * @param  int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Kategori $kategori */
        $kategori = Kategori::find($id);

        if (empty($kategori)) {
            Flash::error('Kategori not found');

            return redirect(route('backend.kategori.index'));
        }

        $kategori->delete();

        Flash::success('Kategori deleted successfully.');

        return redirect(route('backend.kategori.index'));
    }
}

resources/views/backend/roles/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Role</h1>
    </section>
    <div class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                @include('adminlte-templates::common.errors')
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            {!! Form::open(['route' => 'backend.roles.store']) !!}
                                @include('backend.roles.fields')
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>   
        </div>      
    </div>
@endsection

resources/views/backend/roles/datatables_actions.blade.php
{!! Form::open(['route' => ['backend.roles.destroy', $id], 'method' => 'delete']) !!}
    <a href="{{ route('backend.roles.show', $id) }}" class='btn btn-success btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('backend.roles.edit', $id) }}" class='btn btn-info btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
{!! Form::close() !!}

resources/views/backend/roles/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Role
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($role, ['route' => ['backend.roles.update', $role->id], 'method' => 'patch']) !!}

                        @include('backend.roles.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/backend/roles/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Guard Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('guard_name', 'Guard Name:') !!}
    {!! Form::text('guard_name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-12">
    @foreach ($permissions as $permission)
    	<div class="col-md-4">	    	
	    	<div class="form-check form-check-inline">
	    		{{ Form::checkbox('permissions[]',  $permission->id, null, ['class' => 'name'] ) }}
                	{{ Form::label($permission->name) }}

	    	</div>
    	</div>
    @endforeach
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('backend.roles.index') }}" class="btn btn-default">Cancel</a>
</div>



@push('scripts')
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-orange',
            radioClass: 'iradio_square-orange',
            increaseArea: '20%' // optional
        });
    });
</script>
@endpush

resources/views/backend/roles/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Roles</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('backend.roles.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('backend.roles.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection
@push('scripts')
<script>
    $('.custom-select-master').select2()
</script>
    
@endpush

resources/views/backend/roles/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Role</h1>
    </section>
    <div class="content">
        <div class="row" style="padding-left: 20px">
            @include('backend.roles.show_fields')
        </div>
    </div>
@endsection

resources/views/backend/roles/show_fields.blade.php
<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-body">
            <div class="box-tools pull-left">
                <div class="box-title"><h4>Role Name</h4></div>
            </div>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>{!! Form::label('name', 'Name:') !!}</td>
                        <td>{{ $role->name }}</td>
                    </tr>
                    <tr>
                        <td>{!! Form::label('guard_name', 'Guard Name:') !!}</td>
                        <td>{{ $role->guard_name }}</td>
                    </tr>
                </tbody>
            </table>		    		    
        </div>
    </div>
    <a href="{{ route('backend.roles.index') }}" class="btn btn-default">Back</a>  
</div>


<div class="col-md-6">
        <div class="box box-primary">
            <div class="box-body">
                <div class="box-tools pull-left">
                    <div class="box-title"><h4>Permission</h4></div>
                </div>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td class="row">
                                @foreach ($rolePermission as $item)
                                    <div class="col-md-6">
                                        <i class="fa fa-key" aria-hidden="true"></i> {{ $item->name }}
                                    </div>
                                @endforeach
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

resources/views/backend/roles/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush