routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontController@index')->name('front');
Route::get('/kategori/{slug}', 'FrontController@kategori')->name('kategori');
Route::get('/provinsi/{slug}', 'FrontController@provinsi')->name('provinsi');

Route::get('/search', 'FrontController@search');
Route::get('/searchprovinsi', 'FrontController@searchProvinsi')->name('searchprovinsi');


Route::get('/searchmobile', 'FrontController@search');
Route::get('/searchprovinsimobile', 'FrontController@searchProvinsi')->name('searchprovinsimobile');

Route::get('/detail/{slug}', 'FrontController@detail')->name('detail');
Route::post('/detail/{slug}', 'FrontController@comment')->name('comment.store');

Route::get('/donatur', 'FrontController@donatur')->name('donatur');
Route::post('/donatur', 'FrontController@donaturstore')->name('donaturstore');

Route::get('/daftar', 'RegistrasiController@index')->name('daftar');
Route::post('/daftar', 'RegistrasiController@store')->name('daftarsukses');
// Route::get('/daftar', 'RegistrasiController@index')->name('daftar');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->middleware('verified');

// Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:super-admin']], function () {

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:superadmin|admin|yayasan']], function () {
    Route::resource('users', 'Backend\UserController', ["as" => 'backend']);
    Route::resource('roles', 'Backend\RoleController', ["as" => 'backend']);
    Route::resource('permissions', 'Backend\PermissionController', ["as" => 'backend']);
    Route::resource('kategori', 'Backend\KategoriController', ["as" => 'backend']);
    Route::resource('provinsi', 'Backend\ProvinsiController', ["as" => 'backend']);
    Route::resource('konfirmasi', 'Backend\KonfirmasiController', ["as" => 'backend']);
    Route::resource('donatur', 'Backend\DonaturController', ["as" => 'backend']);
    Route::resource('comments', 'Backend\CommentsController', ["as" => 'backend']);
    Route::resource('slide', 'Backend\SlideController', ["as" => 'backend']);

});

Route::group(['prefix' => 'backend', 'middleware' => ['auth', 'role:yayasan|superadmin|admin']], function () {
    Route::resource('yayasan', 'Backend\YayasanController', ["as" => 'backend']);
});




Route::group(['prefix' => 'backend'], function () {
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bank Donation</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('themes/img/iconb.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('themes/img/iconm.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('themes/img/icons.png') }}">

    <link rel="stylesheet" href="{{ mix('themes/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/bootstrap-toggle.min.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/select2.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/themes.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/skins.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/icheck.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/icons.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/ionicons.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/bootstrap-datetimepicker.min.css') }}">
    <link rel="stylesheet" href="{{ mix('themes/css/custom.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">


    @yield('css')
</head>

<body class="skin-purple-light sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <header class="main-header">
            <a href="{{ url('/home') }}" class="logo">
                <img src="{{ asset('themes/img/logobankdonationwhite.png')}}" width="60"><b>Bank Donation</b>
            </a>

            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown tasks-menu">
                            <a href="{{ url('/')}}" class="dropdown-toggle">
                            <i class="fa fa-globe"></i>
                            Front Web</a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @if (empty(Auth::user()->getFirstMediaUrl('avatars')))
                                    <img src="{{ asset('themes/img/user_avatar.png')}}" class="user-image" alt="User Image" />
                                @else
                                    <img src="{{ Auth::user()->getFirstMediaUrl('avatars') }}" class="user-image" alt="User Image"/>
                                @endif
                                <span class="hidden-xs">{{ Auth::user()->name }}</span>
                            </a>
                            <ul class="dropdown-menu">
                                
                                <li class="user-header">
                                    @if (empty(Auth::user()->getFirstMediaUrl('avatars')))
                                        <img src="{{ asset('themes/img/user_avatar.png')}}" class="img-circle" alt="User Image" />
                                    @else
                                        <img src="{{ Auth::user()->getFirstMediaUrl('avatars') }}" class="img-circle" alt="User Image"/>
                                    @endif
                                    <p>
                                        {{ Auth::user()->name }}
                                        <small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{ url('/logout') }}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2020 <a href="#">Bank Donation</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">
                    Bank Donation
                </a>
            </div>
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{{ url('/login') }}">Login</a></li>
                    <li><a href="{{ url('/register') }}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif
    <script src="{{ mix('themes/js/jquery.min.js')}}"></script>
    <script src="{{ mix('themes/js/moment.min.js')}}"></script>
    <script src="{{ mix('themes/js/bootstrap.min.js')}}"></script>
    <script src="{{ mix('themes/js/bootstrap-datetimepicker.js')}}"></script>
    <script src="{{ mix('themes/js/bootstrap-toggle.min.js')}}"></script>
    <script src="{{ mix('themes/js/themes.min.js')}}"></script>
    <script src="{{ mix('themes/js/icheck.min.js')}}"></script>
    <script src="{{ mix('themes/js/select2.min.js')}}"></script>
    @stack('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="{{ mix('themes/css/datatables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ mix('themes/css/buttons.bootstrap.min.css') }}" rel="stylesheet">

resources/views/layouts/datatables_js.blade.php
<script src="{{ mix('themes/js/jquery.datatables.min.js') }}"></script>
<script src="{{ mix('themes/js/datatables.bootstrap.min.js') }}"></script>
<script src="{{ mix('themes/js/datatables.buttons.min.js') }}"></script>
<script src="{{ mix('themes/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ mix('themes/js/buttons.colvis.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bank Donation</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('themes/img/iconb.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('themes/img/iconm.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('themes/img/icons.png') }}">
    <link rel="stylesheet" href="{{ mix('front/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/icofont.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/boxicons.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/remixicon.css') }}">
    {{-- <link rel="stylesheet" href="{{ mix('front/css/owl.css') }}"> --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{{ mix('front/css/animate.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/aos.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/style.min.css') }}">
    <link rel="stylesheet" href="{{ mix('front/css/custom.min.css') }}">


    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">
    @yield('css')
</head>
<body>
    @include('shared.header')
    

    @yield('content')
    @include('shared.footer')

    <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
    <div id="preloader"></div>


    <script src="{{ mix('front/js/jquery.min.js')}}"></script>
    <script src="{{ mix('front/js/bootstrap.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous"></script>    <script src="{{ mix('front/js/jquery.easing.min.js')}}"></script>
    <script src="{{ mix('front/js/jquery.waypoints.min.js')}}"></script>
    <script src="{{ mix('front/js/counterup.min.js')}}"></script>
    <script src="{{ mix('front/js/owl.carousel.min.js')}}"></script>
    <script src="{{ mix('front/js/aos.js')}}"></script>
    <script src="{{ mix('front/js/select2.min.js') }}"></script>

    <script src="{{ asset('front/js/main.js')}}"></script>

    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    <script>
      $('#select_sol').select2({
        placeholder: 'Indonesia',
        theme: 'bootstrap4',        
      }).on('select2:select', function(e){
            var data = e.params.data;
            var selected = $('#select_sol').val();
            var provinces_id = data.id
            console.log(data.id + 'ok' + selected + 'pro' + provinces_id);
            $('#search').submit();

      });

      $('#search_prov').select2({
        placeholder: 'Indonesia',
        theme: 'bootstrap4',
        width: '100%'        
      }).on('select2:select', function(e){
            var data = e.params.data;
            var selected = $('#search_prov').val();
            var provinces_id = data.id
            console.log(data.id + 'ok' + selected + 'pro' + provinces_id);
            $('#provid').submit();

      });

      

    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    @stack('scripts')

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-176402206-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-176402206-1');
    </script>

</body>

</html>

resources/views/layouts/menu.blade.php
@role('superadmin')
<li class="treeview">
	<a href="#"><i class="ic-users"></i> <span>User Manager</span>
		<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
	</a>
    <ul class="treeview-menu">
        <li class="{{ Request::is('backend/users*') ? 'active' : '' }}">
			<a href="{{ route('backend.users.index') }}"><i class="ic-users"></i> <span>Users</span></a>
		</li>

		<li class="{{ Request::is('backend/roles*') ? 'active' : '' }}">
		    <a href="{{ route('backend.roles.index') }}"><i class="ic-shield1"></i> <span>Roles</span></a>
		</li>

		<li class="{{ Request::is('backend/permissions*') ? 'active' : '' }}">
		    <a href="{{ route('backend.permissions.index') }}"><i class="ic-lock_outline"></i> <span>Permissions</span></a>
		</li>
    </ul>
</li>


<li class="{{ Request::is('backend/kategori*') ? 'active' : '' }}">
    <a href="{{ route('backend.kategori.index') }}"><i class="ic-now_widgets"></i> <span>Kategori</span></a>
</li>

<li class="{{ Request::is('backend/provinsi*') ? 'active' : '' }}">
    <a href="{{ route('backend.provinsi.index') }}"><i class="ic-location_on"></i> <span>Provinsi</span></a>
</li>
<li class="{{ Request::is('backend/konfirmasi*') ? 'active' : '' }}">
    <a href="{{ route('backend.konfirmasi.index') }}"><i class="ic-event_note"></i> <span>Konfirmasi Pembayaran</span></a>
</li>
@endrole
@role('yayasan|superadmin')

<li class="{{ Request::is('backend/yayasan*') ? 'active' : '' }}">
    <a href="{{ route('backend.yayasan.index') }}"><i class="ic-codesandbox"></i> <span>Yayasan</span></a>
</li>
@endrole


<li class="{{ Request::is('backend/donatur*') ? 'active' : '' }}">
    <a href="{{ route('backend.donatur.index') }}"><i class="ic-codesandbox"></i> <span>Donatur</span></a>
</li>

<li class="{{ Request::is('backend/comments*') ? 'active' : '' }}">
    <a href="{{ route('backend.comments.index') }}"><i class="fa fa-edit"></i><span>Comments</span></a>
</li>

<li class="{{ Request::is('backend/slide*') ? 'active' : '' }}">
    <a href="{{ route('backend.slide.index') }}"><i class="fa fa-edit"></i><span>Slide</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                @if (empty(Auth::user()->getFirstMediaUrl('avatars')))
                    <img src="{{ asset('themes/img/user_avatar.png')}}" class="img-circle" alt="User Image" />
                @else
                    <img src="{{ Auth::user()->getFirstMediaUrl('avatars') }}" class="img-circle" alt="User Image"/>
                @endif
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>Polisi Apps</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
    </section>
</aside>